search_config:
  endpoint: "https://chris-rag-testing.search.azure.us"
  api_key: AZURE_SEARCH_KEY

embedding:
  endpoint: "https://ai-aifoundryarizona750873844815.openai.azure.us/openai/deployments/text-embedding-3-large/embeddings?api-version=2023-05-15"
  api_key: AZURE_LLM_API_KEY_ARIZONA
  api_version: "2024-02-01"
  model: "text-embedding-3-large"

